### ISSUE TITLE
Allure plugin not showing report - Jenkinsfile Pipeline

### ISSUE THREAD

**Issue by sachindast** [jenkinsci/allure-plugin#269]
Hello Team,

Reporting the issue  on Auget 2020
---------------------------------------------
Issue still seeing in Jenkins - log says Allure report was successfully generated but empty report coming, same is working with normal Jenkins job that uses post-build section to perform allure reports. 

Jenkins version          : 2.209
allure plugin version : 2.28.1

below is a snippet of the problem

**Report successfully generated to /home/allure_pipeline/allure-report
Allure report was successfully generated.
Creating artifact for the build.
Artifact was added to the build.**

i'm using within post build section as below : 

 **always {
            node('build-machine')
                {
                sh 'mkdir -p $WORKSPACE/{allure-report,reports}'
                allure includeProperties: false, jdk: '', results: [[path: 'reports/']]
                }
            }**

even I have tried by putting it as a stage.

**tage('reports') {
    steps {
    script {
            allure([
                    includeProperties: false,
                    jdk: '',
                    properties: [],
                    reportBuildPolicy: 'ALWAYS',
                    results: [[path: 'reports/']]
            ])
    }
    }
}**

I have tried most of the possible ways, let me know if there are any problems the way I'm doing?

Thanks in advance,
Sachin Das 
![jenkins_allure_report](https://user-images.githubusercontent.com/29208125/89518534-a6e35900-d7f8-11ea-95f5-da3e29994dca.png)

**Comment by 4n70w4** [comment]
The same issue. May be similar https://github.com/allure-framework/allure2/issues/1133

**Comment by Vodrech** [comment]
When I created the allure report through jenkins pipeline it seemed to work correctly, but then I looked into the GUI configurations and the path were set to "allure-results" instead of the given parameter path "target/allure-results".  It seems that it doesn't take in the parameters.

1.) Must I specify the other params, or can't I just specify one?
2.) And is there something with the publisher that is causing the problem?

_Note: I tried with all the sugest parameters but it still didn't work._

reference for publisher allure:
https://docs.openstack.org/infra/jenkins-job-builder/publishers.html ( Think its from 2014 but not sure )

```
 publishers {
            allure {
                results([path:'target/allure-results'])
                }
            }
```

_Guidance:_ If someone gets NaN% in the report on jenkins, look into the results --> path and make sure its pointing to target/allure-reports and not just allure-reports.


_Note: This is just for the "General configurations, if you have set to another path/location maybe something else is causing it"._


If someone got any advice, its recommended to write those below! Still in search after a solution to auto generate the correct path for allure :(.
