### ISSUE TITLE
jenkins could not generate report

### ISSUE THREAD

**Issue by fengzhou** [jenkinsci/allure-plugin#51]
jenkins version 1.65.1.1
java version 1.7

the error message :
[allure_demo] $ "C:\Program Files (x86)\Jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\latest\bin\allure.bat" generate "E:\work\py_api\reportxml\2016-05-11\2016-05-11-14_45_16" "E:\report" '"C:\Program Files (x86)\Jenkins\workspace\allure_demo\allure2086714799224107849.tmp\environment"' -o '"C:\Program Files (x86)\Jenkins\workspace\allure_demo\allure2086714799224107849.tmp\allure-report"'
此时不应有 \Jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\latest。

i don't know how to fix it.

**Comment by sudheerkb** [comment]
I am too getting the same issue.
@fengzhou where you able to fix this issue? if so, could you please help me in fixing this.

**Comment by baev** [comment]
@sudheerkb I am going to fix this in #62

**Comment by sudheerkb** [comment]
Thank you @baev 
We are planning to effictively use Allure reporting in our UI and API test automation.
Ours is a small company and i am the only automation engineer. I have little knowledge on maven and jenkins. I am trying to set allure reporting with the help of examples section.If i need any immediate assistance, what would be the best way to communicate with you guys.

Thanks,
Sudheer

**Comment by monolithed** [comment]
Oh, we have the same problem:

<details>
<summery>
Log
</summery>

14:14:21 [yoda.runner] $ /var/lib/selenium/jenkins-slave/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/1.4.24RC3-NEWFACE/bin/allure generate "/var/lib/selenium/jenkins-slave/workspace/yoda.runner/tests/cache/reports/allure-results" "/var/lib/selenium/jenkins-slave/workspace/yoda.runner/allure6050067575725090175.tmp/environment" -o "/var/lib/selenium/jenkins-slave/workspace/yoda.runner/allure6050067575725090175.tmp/allure-report"
14:14:26 Exception in thread "main" java.lang.NumberFormatException: For input string: ""
14:14:26 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
14:14:26 	at java.lang.Long.parseLong(Long.java:601)
14:14:26 	at java.lang.Long.valueOf(Long.java:803)
14:14:26 	at com.sun.xml.internal.bind.DatatypeConverterImpl._parseLong(DatatypeConverterImpl.java:118)
14:14:26 	at ru.yandex.qatools.allure.model.TestCaseResult_JaxbXducedAccessor_stop.parse(TransducedAccessor_field_Long.java:50)
14:14:26 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StructureLoader.startElement(StructureLoader.java:195)
14:14:26 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:559)
14:14:26 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538)
14:14:26 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:153)
14:14:26 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
14:14:26 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:380)
14:14:26 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2781)
14:14:26 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
14:14:26 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
14:14:26 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
14:14:26 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
14:14:26 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
14:14:26 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
14:14:26 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
14:14:26 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
14:14:26 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
14:14:26 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:221)
14:14:26 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:276)
14:14:26 	at javax.xml.bind.JAXB.unmarshal(JAXB.java:242)
14:14:26 	at ru.yandex.qatools.allure.commons.AllureFileUtils.unmarshal(AllureFileUtils.java:59)
14:14:26 	at ru.yandex.qatools.allure.commons.AllureFileUtils.unmarshal(AllureFileUtils.java:50)
14:14:26 	at ru.yandex.qatools.allure.commons.AllureFileUtils.unmarshal(AllureFileUtils.java:40)
14:14:26 	at ru.yandex.qatools.allure.data.io.TestSuiteReader$TestSuiteResultIterator.next(TestSuiteReader.java:48)
14:14:26 	at ru.yandex.qatools.allure.data.io.TestSuiteReader$TestSuiteResultIterator.next(TestSuiteReader.java:1)
14:14:26 	at ru.yandex.qatools.allure.data.io.TestCaseReader$TestCaseResultIterator.nextSuite(TestCaseReader.java:46)
14:14:26 	at ru.yandex.qatools.allure.data.io.TestCaseReader$TestCaseResultIterator.hasNext(TestCaseReader.java:56)
14:14:26 	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:63)
14:14:26 	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:53)
14:14:26 	at ru.yandex.qatools.allure.AllureMain.main(AllureMain.java:48)
14:14:26 Command aborted due to exception {}.
14:14:26 org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
14:14:26 	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
14:14:26 	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
14:14:26 	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
14:14:26 	at ru.yandex.qatools.allure.command.ReportGenerate.runUnsafe(ReportGenerate.java:48)
14:14:26 	at ru.yandex.qatools.allure.command.AbstractCommand.run(AbstractCommand.java:52)
14:14:26 	at ru.yandex.qatools.allure.CommandLine.main(CommandLine.java:46)
14:14:26 Build step 'Allure Report' marked build as failure
14:14:26 Finished: FAILURE
</details>

**Comment by PrasannaAtLearnyst** [comment]
@baev is this issue solved? we are facing the same issue.
